apiVersion: v1
kind: Secret
metadata:
  name: ecmwf-credentials
  namespace: xrsc07
type: Opaque
stringData:
  credentials.json: |
    {
      	"ecmwf-open": {
          "url"   : "https://data.ecmwf.int/forecasts"
        }
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: xrsc07
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "itachuva"