# Cria uma service account para o namespace xrsc07
# É a conta a qual os workflows do pipeline irão utilizar, permitindo-os criar e gerenciar os pods deste namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: xrsc07

---

#Vincula a Cluster Role de criar e gerenciar pods à conta do argo para o namespace xrsc07
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-executor-binding
  namespace: xrsc07
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-executor-rbac
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: xrsc07